algo= input('Digite algo: ')
print('O tipo primitivo de {} é {}.'.format(algo, type(algo)))
print('{} só tem espaços: {}.'.format(algo, algo.isspace()))
print('{} é um número: {}.'.format(algo, algo.isnumeric()))
print('{} é alfabético: {}.'.format(algo, algo.isalpha()))
print('{} é alfanumérico: {}.'.format(algo, algo.isalnum()))
print('{} é maiúscula: {}.'.format(algo, algo.isupper()))
print('{} é menúscula: {}.'.format(algo, algo.islower()))
print('{} é capitalizada: {}.'.format(algo, algo.istitle()))
